### ISSUE TITLE
Failture over bam file analysis

### ISSUE THREAD

**Issue by Tiezhengyuan** [wdecoster/NanoPlot#85] opened 2018-08-24 19:28 UTC
$ NanoPlot  --bam ./LAseriesFieldRoots/L1/L1.bam 
Process Process-1:
Traceback (most recent call last):
  File "/anaconda/envs/py35/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/anaconda/envs/py35/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/anaconda/envs/py35/lib/python3.5/concurrent/futures/process.py", line 181, in _process_worker
    result=r))
  File "/anaconda/envs/py35/lib/python3.5/multiprocessing/queues.py", line 355, in put
    self._writer.send_bytes(obj)
  File "/anaconda/envs/py35/lib/python3.5/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/anaconda/envs/py35/lib/python3.5/multiprocessing/connection.py", line 393, in _send_bytes
    header = struct.pack("!i", n)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647

If you read this then NanoPlot has crashed :-(
Please report this issue at https://github.com/wdecoster/NanoPlot/issues
If you include the log file that would be really helpful.
Thanks!

Traceback (most recent call last):
  File "/home/superuser/.local/bin/NanoPlot", line 11, in <module>
    sys.exit(main())
  File "/home/superuser/.local/lib/python3.5/site-packages/nanoplot/NanoPlot.py", line 63, in main
    barcoded=args.barcoded)
  File "/home/superuser/nanoget.py", line 74, in get_input
    dfs=[out for out in executor.map(extration_function, files)],
  File "/home/superuser/nanoget.py", line 74, in <listcomp>
    dfs=[out for out in executor.map(extration_function, files)],
  File "/anaconda/envs/py35/lib/python3.5/concurrent/futures/_base.py", line 556, in result_iterator
    yield future.result()
  File "/anaconda/envs/py35/lib/python3.5/concurrent/futures/_base.py", line 405, in result
    return self.__get_result()
  File "/anaconda/envs/py35/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.

**Comment by wdecoster** [comment] 2018-08-24 19:36
Potential duplicate of https://github.com/wdecoster/NanoPlot/issues/81

Which version of NanoPlot are you using? If it's <1.16.0 then please update.

Are you using a pretty large bam file here?

**Comment by Tiezhengyuan** [comment] 2018-08-25 12:55
Thank you for your help. The currently installed version is 1.14.2, and Iwill update to the newest version and try again.
The size of the bam file I tested is 4.5G
Tiezheng
________________________________
发件人: Wouter De Coster <notifications@github.com>
发送时间: 2018年8月25日 3:36
收件人: wdecoster/NanoPlot
抄送: Tiezhengyuan; Author
主题: Re: [wdecoster/NanoPlot] Failture over bam file analysis (#85)


Potential duplicate of #81<https://github.com/wdecoster/NanoPlot/issues/81>

Which version of NanoPlot are you using? If it's <1.16.0 then please update.

Are you using a pretty large bam file here?

―

**Comment by wdecoster** [comment] 2018-09-17 19:30
Did this help?

**Comment by Tiezhengyuan** [comment] 2018-09-17 19:50
Hi,

I did update to NanoPlot v 1.17.1. However, that still failed.  I am trying to contact with my collaborator and ask for another bam file. I  will keep you posted once I have done everything.
Additionaly,  the bam file comes from hisat2 results over mRNA-seq with paired-end sequencing.

Thanks

Tiezheng

________________________________
发件人: Wouter De Coster <notifications@github.com>
发送时间: 2018年9月18日 3:30
收件人: wdecoster/NanoPlot
抄送: Tiezhengyuan; Author
主题: Re: [wdecoster/NanoPlot] Failture over bam file analysis (#85)


Did this help?

―

**Comment by wdecoster** [comment] 2018-09-17 20:26
> Additionaly, the bam file comes from hisat2 results over mRNA-seq with paired-end sequencing.

I do not consider that 'additionally'. NanoPlot is written for plotting results of long read sequencing data, of which the characteristics are of course very different than paired-end short read mRNA sequencing. You probably have a lot more reads in your experiment than what is typical for long read sequencing, hence the failure. NanoPlot is not written for these amounts, unfortunately.

If you insist on using NanoPlot the best way forward would be to downsample your bam file, which you can do with samtools.

Cheers,
Wouter

**Comment by Tiezhengyuan** [comment] 2018-09-17 20:34
thank your for suggestions. I could try then. Tiezheng
________________________________
发件人: Wouter De Coster <notifications@github.com>
发送时间: 2018年9月18日 4:26
收件人: wdecoster/NanoPlot
抄送: Tiezhengyuan; Author
主题: Re: [wdecoster/NanoPlot] Failture over bam file analysis (#85)


Additionaly, the bam file comes from hisat2 results over mRNA-seq with paired-end sequencing.

I do not consider that 'additionally'. NanoPlot is written for plotting results of long read sequencing data, of which the characteristics are of course very different than paired-end short read mRNA sequencing. You probably have a lot more reads in your experiment than what is typical for long read sequencing, hence the failure. NanoPlot is not written for these amounts, unfortunately.

If you insist on using NanoPlot the best way forward would be to downsample your bam file, which you can do with samtools.

Cheers,
Wouter

―

**Closed** 2018-09-24 08:55 UTC
Labels: duplicate
