### ISSUE TITLE
Nanoplot Error

### ISSUE THREAD

**Issue by kminie** [wdecoster/NanoPlot#1] opened 2017-06-07 11:26 UTC
Hi I am facing following error while using Nanoplot, following is my command -

`NanoPlot --fastq barcode1.fastq`

and following is error I have got -
```
Traceback (most recent call last):
  File "/usr/local/bin/NanoPlot", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/nanoplot/NanoPlot.py", line 45, in main
    makePlots(datadf, lengthprefix, logBool, readlengthsPointer, args, stamp)
  File "/usr/local/lib/python2.7/dist-packages/nanoplot/NanoPlot.py", line 191, in makePlots
    log=logBool)
  File "/usr/local/lib/python2.7/dist-packages/nanoplotter/nanoplotter.py", line 36, in scatter
    size=10)
  File "/usr/local/lib/python2.7/dist-packages/seaborn-0.7.1-py2.7.egg/seaborn/distributions.py", line 798, in jointplot
    xlim=xlim, ylim=ylim)
  File "/usr/local/lib/python2.7/dist-packages/seaborn-0.7.1-py2.7.egg/seaborn/axisgrid.py", line 1624, in __init__
    f = plt.figure(figsize=(size, size))
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 535, in figure
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_tkagg.py", line 81, in new_figure_manager
    return new_figure_manager_given_figure(num, figure)
  File "/usr/local/lib/python2.7/dist-packages/matplotlib/backends/backend_tkagg.py", line 89, in new_figure_manager_given_figure
    window = Tk.Tk()
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1818, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: no display name and no $DISPLAY environment variable

```

**Comment by wdecoster** [comment] 2017-06-07 12:23
Thanks for the report.

The Tcl/Tk error makes me wonder, but this might have a similar cause as [your issue with NanoFilt](https://github.com/wdecoster/nanofilt/issues/1). Again, NanoPlot was written for Python3. Could you try again if the error is reproduced or fixed with Python3? Perhaps I should have the script explicitly check for the right version.

Another possible cause: are you working on a server without X?

Please let me know what the result is after trying Python3 so we can nail this down, and hopefully solve the issue.

**Comment by kminie** [comment] 2017-06-08 09:08
Ahh ..the cause was working without X, it seems to work fine with  Python 2.7 as well...
Thanks

**Closed** 2017-06-08 09:08 UTC

**Comment by BenjaminSchwessinger** [comment] 2017-06-08 13:08
I had the same issue on our cluster which does not have ssh -X display options. I added the following line the beginning of your script.
import matplotlib
matplotlib.use('Agg')
based on https://stackoverflow.com/questions/37604289/tkinter-tclerror-no-display-name-and-no-display-environment-variable

working just fine now on the cluster. Nice looking plots! Will play around a bit more. Thanks!

**Comment by wdecoster** [comment] 2017-06-09 08:13
Thanks for the feedback, since our servers have X I hadn't encountered this issue. I'll make sure to add those lines in the next release.
