### ISSUE TITLE
Error in running nanoplot .Doesnot produce combined result file.

### ISSUE THREAD

**Issue by ap1438** [wdecoster/NanoPlot#344] opened 2023-10-19 10:53 UTC
I was using it previously without any error but this time its giving error.
I installed it using conda.

`/vol/pac/Software/anaconda3/envs/nanoplot/lib/python3.7/site-packages/nanoplotter/nanoplotter_main.py:283: UserWarning: 

`distplot` is a deprecated function and will be removed in seaborn v0.14.0.

Please adapt your code to use either `displot` (a figure-level function with
similar flexibility) or `histplot` (an axes-level function for histograms).

For a guide to updating your code to use the new functions, please see
https://gist.github.com/mwaskom/de44147ed2974457ad6372750bbe5751

  alpha=0.8))
/vol/pac/Software/anaconda3/envs/nanoplot/lib/python3.7/site-packages/nanoplotter/nanoplotter_main.py:308: UserWarning: 

`distplot` is a deprecated function and will be removed in seaborn v0.14.0.

Please adapt your code to use either `displot` (a figure-level function with
similar flexibility) or `histplot` (an axes-level function for histograms).

For a guide to updating your code to use the new functions, please see
https://gist.github.com/mwaskom/de44147ed2974457ad6372750bbe5751

  alpha=0.8))

If you read this then NanoPlot 1.32.1 has crashed :-(
Please try updating NanoPlot and see if that helps...

If not, please report this issue at https://github.com/wdecoster/NanoPlot/issues
If you could include the log file that would be really helpful.
Thanks!

Traceback (most recent call last):
  File "/vol/pac/Software/anaconda3/envs/nanoplot/bin/NanoPlot", line 10, in <module>
    sys.exit(main())
  File "/vol/pac/Software/anaconda3/envs/nanoplot/lib/python3.7/site-packages/nanoplot/NanoPlot.py", line 101, in main
    plots = make_plots(datadf, settings)
  File "/vol/pac/Software/anaconda3/envs/nanoplot/lib/python3.7/site-packages/nanoplot/NanoPlot.py", line 169, in make_plots
    plot_settings=plot_settings)
  File "/vol/pac/Software/anaconda3/envs/nanoplot/lib/python3.7/site-packages/nanoplotter/nanoplotter_main.py", line 169, in scatter
    joint_kws={"s": 1})
  File "/vol/pac/Software/anaconda3/envs/nanoplot/lib/python3.7/site-packages/seaborn/axisgrid.py", line 2255, in jointplot
    grid.plot_joint(scatterplot, **joint_kws)
  File "/vol/pac/Software/anaconda3/envs/nanoplot/lib/python3.7/site-packages/seaborn/axisgrid.py", line 1826, in plot_joint
    func(x=self.x, y=self.y, **kwargs)
  File "/vol/pac/Software/anaconda3/envs/nanoplot/lib/python3.7/site-packages/seaborn/relational.py", line 761, in scatterplot
    p.plot(ax, kwargs)
  File "/vol/pac/Software/anaconda3/envs/nanoplot/lib/python3.7/site-packages/seaborn/relational.py", line 573, in plot
    points = ax.scatter(x=x, y=y, **kws)
  File "/vol/pac/Software/anaconda3/envs/nanoplot/lib/python3.7/site-packages/matplotlib/__init__.py", line 1414, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/vol/pac/Software/anaconda3/envs/nanoplot/lib/python3.7/site-packages/matplotlib/axes/_axes.py", line 4467, in scatter
    collection.update(kwargs)
  File "/vol/pac/Software/anaconda3/envs/nanoplot/lib/python3.7/site-packages/matplotlib/artist.py", line 1067, in update
    raise AttributeError(f"{type(self).__name__!r} object "
AttributeError: 'PathCollection' object has no property 'stat_func'
`

**Comment by wdecoster** [comment] 2023-10-19 20:28
This is a duplicate of https://github.com/wdecoster/NanoPlot/issues/222

Please downgrade your seaborn installation to 0.10.1

**Closed by wdecoster** 2023-10-19 20:28 UTC
