### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by smm19900210** [wdecoster/NanoPlot#89] opened 2018-09-14 05:29 UTC
hi wdecoster, i met a problem, my command is `NanoPlot --fastq ../test.fastq --plots hex dot`
below is the log file 

Traceback (most recent call last):
  File "/share/nas2/genome/biosoft/Python/3.4.3/bin/NanoPlot", line 11, in <module>
    load_entry_point('NanoPlot==1.0.0', 'console_scripts', 'NanoPlot')()
  File "/share/nas2/genome/biosoft/Python/3.4.3/lib/python3.4/site-packages/NanoPlot-1.0.0-py3.4.egg/nanoplot/NanoPlot.py", line 62, in main
    nanomath.write_stats(datadf, settings["path"] + "NanoStats.txt")
  File "/share/nas2/genome/biosoft/Python/3.4.3/lib/python3.4/site-packages/nanomath/nanomath.py", line 136, in write_stats
    stats = [Stats(df) for df in datadfs]
  File "/share/nas2/genome/biosoft/Python/3.4.3/lib/python3.4/site-packages/nanomath/nanomath.py", line 136, in <listcomp>
    stats = [Stats(df) for df in datadfs]
  File "/share/nas2/genome/biosoft/Python/3.4.3/lib/python3.4/site-packages/nanomath/nanomath.py", line 31, in __init__
    self.number_of_bases = np.sum(df["lengths"])
TypeError: string indices must be integers

**Comment by wdecoster** [comment] 2018-09-14 08:41
Duplicate of https://github.com/wdecoster/NanoPlot/issues/21

Please try `pip install -U statsmodels`

**Comment by wdecoster** [comment] 2018-09-21 13:17
Can you let me know if that solved the issue?

**Comment by JohnalphaFox** [comment] 2018-09-22 18:50
y_train = geometry_types[0:abs((1-test_split)*dataset_size)]

TypeError: slice indices must be integers or None or have an __index__ method

can it be solved

**Comment by wdecoster** [comment] 2018-09-22 21:01
That seems unrelated to this issue?

Anyway, check what `abs((1-test_split)*dataset_size)` is, it should be an integer.

**Closed** 2018-09-30 18:42 UTC
Labels: duplicate
