### ISSUE TITLE
NanoPlot_20201111_0039

### ISSUE THREAD

**Issue by lynch-zs** [wdecoster/NanoPlot#216] opened 2020-11-10 16:49 UTC
[NanoPlot_20201111_0039.log](https://github.com/wdecoster/NanoPlot/files/5518849/NanoPlot_20201111_0039.log)

**Comment by wdecoster** [comment] 2020-11-10 18:29
Duplicate of https://github.com/wdecoster/NanoPlot/issues/201

**Closed by wdecoster** 2020-11-10 18:29 UTC
