### ISSUE TITLE
TypeError: slice indices must be integers or None or have an __index__ method

### ISSUE THREAD

**Issue by wzylin** [wdecoster/NanoPlot#45] opened 2018-02-08 04:54 UTC
Hi,
I cannot plot kernel graph, any help?
Thank you!

Traceback (most recent call last):
  File "/home/wzylin/anaconda3/bin/NanoPlot", line 11, in <module>
    sys.exit(main())
  File "/home/wzylin/anaconda3/lib/python3.5/site-packages/nanoplot/NanoPlot.py", line 86, in main
    plots = make_plots(datadf, settings)
  File "/home/wzylin/anaconda3/lib/python3.5/site-packages/nanoplot/NanoPlot.py", line 359, in make_plots
    title=settings["title"])
  File "/home/wzylin/anaconda3/lib/python3.5/site-packages/nanoplotter/nanoplotter.py", line 192, in scatter
    size=10)
  File "/home/wzylin/anaconda3/lib/python3.5/site-packages/seaborn/axisgrid.py", line 2275, in jointplot
    grid.plot_marginals(kdeplot, **marginal_kws)
  File "/home/wzylin/anaconda3/lib/python3.5/site-packages/seaborn/axisgrid.py", line 1780, in plot_marginals
    func(self.x, **kwargs)
  File "/home/wzylin/anaconda3/lib/python3.5/site-packages/seaborn/distributions.py", line 657, in kdeplot
    cumulative=cumulative, **kwargs)
  File "/home/wzylin/anaconda3/lib/python3.5/site-packages/seaborn/distributions.py", line 273, in _univariate_kdeplot
    cumulative=cumulative)
  File "/home/wzylin/anaconda3/lib/python3.5/site-packages/seaborn/distributions.py", line 345, in _statsmodels_univariate_kde
    kde.fit(kernel, bw, fft, gridsize=gridsize, cut=cut, clip=clip)
  File "/home/wzylin/anaconda3/lib/python3.5/site-packages/statsmodels/nonparametric/kde.py", line 146, in fit
    clip=clip, cut=cut)
  File "/home/wzylin/anaconda3/lib/python3.5/site-packages/statsmodels/nonparametric/kde.py", line 506, in kdensityfft
    f = revrt(zstar)
  File "/home/wzylin/anaconda3/lib/python3.5/site-packages/statsmodels/nonparametric/kdetools.py", line 20, in revrt
    y = X[:m/2+1] + np.r_[0,X[m/2+1:],0]*1j
TypeError: slice indices must be integers or None or have an __index__ method

**Comment by wdecoster** [comment] 2018-02-08 09:40
This sounds like a duplicate of https://github.com/wdecoster/NanoPlot/issues/21, could you try what I recommended [here](https://github.com/wdecoster/NanoPlot/issues/21#issuecomment-340665698)?

**Comment by wzylin** [comment] 2018-02-08 17:52
it works, thank you!

**Comment by wdecoster** [comment] 2018-02-08 17:57
Good to hear. Please let me know if you have more feedback or feature requests!

**Closed by wdecoster** 2018-02-08 17:57 UTC
