### ISSUE TITLE
ValueError: Transform failed with error code 1: Failed to serialize document: Uncaught

### ISSUE THREAD

**Issue by EinarBaldvin** [wdecoster/NanoPlot#207] opened 2020-09-17 17:51 UTC
Hi Wouter,

I am using the latest version installed via pip (PyPi) and keep getting the same error at the end of plot generation. Is this a bug or something wrong locally?

Command: NanoPlot -t 4 --fastq_rich g0044_Q7_G4.0.11.fastq.gz --loglength -o nanoplot_test

Attached are both the log and python packages installed.

[NanoPlot_20200917_1923.log](https://github.com/wdecoster/NanoPlot/files/5240906/NanoPlot_20200917_1923.log)
[requirements.txt](https://github.com/wdecoster/NanoPlot/files/5240991/requirements.txt)

Thanks for this great tool!

Best wishes,
Einar

**Comment by wdecoster** [comment] 2020-09-17 18:33
Thanks for reporting this, I'll have to investigate. I recently switched to kaleido to create the static versions of HTML plots. If you install v1.32.1 things should just work (`pip install NanoPlot==1.32.1`). My apologies for the inconvenience.

**Comment by EinarBaldvin** [comment] 2020-09-18 13:31
Thanks for the quick response.

Downgrading solved the issue.

Best,
Einar

**Comment by EinarBaldvin** [comment] 2020-09-18 14:34
Yes, the HPC is blocked from the internet and not sure when they will open direct internet access again.

But why would the the plotly(kaleido) package need internet access?

**Comment by EinarBaldvin** [comment] 2020-09-18 14:56
Great to hear. It would be preferable that it would not need to connect to the internet.

Thank you for the help!

**Comment by jonmmease** [comment] 2020-09-18 16:48
> But why would the the plotly(kaleido) package need internet access?

Just wanted to include a little context. With Kaleido, the image export process itself is fully offline and your figure data is *never* sent over the network. Several years ago there was a image export API in plotly.py that used a network request to perform the image export on plotly's servers, so I just wanted to be clear that this isn't happening with Kaleido.

What's going on here is that we don't include the plotly.js JavaScript library in the Kaleido package. This is because Kaleido is a pretty large package, and we don't want to need to release it every time a new version of plotly.py/plotly.js is released. By default Kaleido will pull plotly.js from the public online CDN at https://cdn.plot.ly/plotly-latest.min.js. But the caller of Kaleido can provide a path to a local version of plotly.js, and this is what `plotly.py` does (as of version 4.9.0).

**Comment by Thomieh73** [comment] 2020-10-08 09:04
Hi, I just want to indicate that I now also ran into this error. And on our HPC active jobs do not have internet access. The error does not occure when I am running the program on the login node.

**Comment by wdecoster** [comment] 2020-10-08 09:10
Thanks for reporting this, I'll prioritize this to get this fixed soon.

**Comment by wdecoster** [comment] 2020-10-09 07:13
Hi all,

This issue should be resolved in NanoPlot v1.33.1, which is now available on PyPI. Please let me know if you encounter further errors.

Regards,
Wouter

**Closed by wdecoster** 2020-10-09 07:13 UTC

**Comment by sulheim** [comment] 2021-04-12 12:13
Hi Wouter!

I think I run into the same issue with NanoPlot 1.35.5. I run NanoPlot on WSL. See attached log file and list of package versions.
All the generated png files are empty.

Regards,
Snorre
[NanoPlot_20210412_1330.log](https://github.com/wdecoster/NanoPlot/files/6296546/NanoPlot_20210412_1330.log)
[packages.txt](https://github.com/wdecoster/NanoPlot/files/6296547/packages.txt)

**Comment by wdecoster** [comment] 2021-04-12 12:23
Thanks for letting me know, unfortunately the kaleido errors are not something that I can fix.

**Comment by wdecoster** [comment] 2021-04-12 12:39
@iliasbukraa can you look into deleting the png file if the except clause is triggered in Plot.save(), while first checking if they exist?

**Comment by sulheim** [comment] 2021-04-12 13:42
Okey, so if I understand you correctly this is a known error caused by Kaileido? With an open issue?

**Comment by wdecoster** [comment] 2021-04-12 14:06
Similar errors have been reported:
https://github.com/JuliaPlots/PlotlyJS.jl/issues/357
https://github.com/plotly/Kaleido/issues/41 (issue opened by me, but should be solved)

**Comment by mike-molnar** [comment] 2021-05-08 05:09
Hi Wouter,

I am getting the same error when I run version 1.36.2 on a node without internet access.  It works fine when running on a node with internet access.  I was going to change it to output pdf instead of png, but the -f option has been removed.  Would it be possible to add that option back?

Thanks,
Mike

**Comment by mike-molnar** [comment] 2021-05-09 02:30
The error I get is:
2021-05-08 00:44:26,343 No static plots are saved due to some kaleido problem:
2021-05-08 00:44:26,344 Transform failed with error code 1: Failed to serialize document: Uncaught

Nanoplot finishes everything else, so it isn't crashing.  I am running Nanoplot through snakemake, and an error is reported to snakemake.  The image I want is {prefix}LengthvsQualityScatterPlot_loglength_kde.png, which I would prefer as a pdf if writing png's is not possible through the cluster, since it doesn't have internet access.  I don't use the reports right now, but I would prefer them in pdf too if possible.

Also, the LengthvsQualityScatterPlot_loglength_kde file that gets written with the newest version looks different than before (like the plot on Nanoplot's homepage).  Has the settings changed for how that file looks?  I have rebuilt my conda environment, so it could just be that I have not installed the proper libraries for writing the png's properly.

Thanks again,
Mike

**Comment by wdecoster** [comment] 2021-05-09 18:46
Thanks for clarifying - could you let me know the version of your plotly installation?

You should be able to get that with `python -c import plotly : print(plotly.__version__)`.
And if that is <4.9, could you try upgrading to 4.9 or higher and test again?

Yes, plots look different know, as we are using plotly as often as we can and got rid of the dependencies seaborn and matplotlib. To get the 'older style' plots there is a `--legacy` option (I should really update the documentation). These do however still require seaborn and matplotlib, which you then have to make sure are installed (as they are no longer installed by default when installing NanoPlot...)

Cheers,
Wouter

**Comment by mike-molnar** [comment] 2021-05-11 04:31
I was using plotly version 4.14.3.  Using the `--legacy kde` flag and downgrading my seaborn to 0.10.1 did the trick.  The legacy plots are what I was looking for and they look like the old style plots.  I find the new plots more informative, just not as visual appealing.

Unfortunately, I have to run it on a node with internet access for it all to work.  That's okay though, I'll just change the workflow so each job can select a different queue.  Thanks for all your help Wouter!

Cheers,
Mike

**Comment by wdecoster** [comment] 2021-05-11 06:31
Glad that you could fix it, but it is all rather inconvenient. Thanks for the feedback on the legacy plots - I wish we could recreate them more like the older style, but since that seems to be harder in plotly we decided to keep them in as is.

I'll tag @jonmmease here to ask if he has any insight in the kaleido problem...
To summarize: @mike-molnar is using plotly 4.14.3, and has the `ValueError: Transform failed with error code 1: Failed to serialize document: Uncaught` error (which I catch in a try-except block) if he runs this tool on nodes without internet access. I believe the relevant code is here: https://github.com/wdecoster/NanoPlot/blob/master/nanoplotter/plot.py#L69

Thanks in advance!

Wouter
