### ISSUE TITLE
dependencies missing after pip install NanoPlot and pip install NanoPlot --upgrade

### ISSUE THREAD

**Issue by michael-liem** [wdecoster/NanoPlot#287] opened 2022-02-22 10:32 UTC
I created an conda environment with the following nanoplot.yml file:

name: nanoplot
dependencies:
-python=3.8

create environment
$conda env create --file nanoplot.yml
$conda activate nanoplot

install and upgrade nanoplot
$pip install NanoPlot
$pip install NanoPlot --upgrade

hereafter I got an error message indicating matplotlib and seaborn was not installed, I tried to fix it with:
$python -m pip install --user matplotlib seaborn

at this point I do get a plot (yeah) but there are still error messages showing up:
 NanoPlot -t 10 --fastq ~/file.fastq --maxlength 40000 --plots dot --legacy hex

If you read this then NanoPlot 1.39.0 has crashed :-(
Please try updating NanoPlot and see if that helps...

If not, please report this issue at https://github.com/wdecoster/NanoPlot/issues
If you could include the log file that would be really helpful.
Thanks!

Traceback (most recent call last):
  File "/home/michael/miniconda3/envs/daur2/bin/NanoPlot", line 8, in <module>
    sys.exit(main())
  File "/home/michael/miniconda3/envs/daur2/lib/python3.8/site-packages/nanoplot/NanoPlot.py", line 109, in main
    plots = make_plots(datadf, settings)
  File "/home/michael/miniconda3/envs/daur2/lib/python3.8/site-packages/nanoplot/NanoPlot.py", line 181, in make_plots
    nanoplotter.scatter(
  File "/home/michael/miniconda3/envs/daur2/lib/python3.8/site-packages/nanoplotter/nanoplotter_main.py", line 172, in scatter
    plots_made += scatter_legacy(x=x[idx],
  File "/home/michael/miniconda3/envs/daur2/lib/python3.8/site-packages/nanoplotter/nanoplotter_main.py", line 231, in scatter_legacy
    plot = sns.jointplot(
  File "/home/michael/miniconda3/envs/daur2/lib/python3.8/site-packages/seaborn/_decorators.py", line 46, in inner_f
    return f(**kwargs)
  File "/home/michael/miniconda3/envs/daur2/lib/python3.8/site-packages/seaborn/axisgrid.py", line 2300, in jointplot
    grid.plot_joint(plt.hexbin, **joint_kws)
  File "/home/michael/miniconda3/envs/daur2/lib/python3.8/site-packages/seaborn/axisgrid.py", line 1808, in plot_joint
    func(self.x, self.y, **kwargs)
  File "/home/michael/.local/lib/python3.8/site-packages/matplotlib/pyplot.py", line 2572, in hexbin
    __ret = gca().hexbin(
  File "/home/michael/.local/lib/python3.8/site-packages/matplotlib/__init__.py", line 1412, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/home/michael/.local/lib/python3.8/site-packages/matplotlib/axes/_axes.py", line 4824, in hexbin
    collection.update(kwargs)
  File "/home/michael/.local/lib/python3.8/site-packages/matplotlib/artist.py", line 1064, in update
    raise AttributeError(f"{type(self).__name__!r} object "
AttributeError: 'PolyCollection' object has no property 'stat_func'

Hope this helps to improve,

Cheers,
Michael

p.s. I just figured out then when I omit the flag --legacy hex no error messages occur

**Comment by wdecoster** [comment] 2022-02-22 13:09
I am a little confused why you are installing things both with conda and pip. I would recommend you stick to one of those installation methods. 

The error you report is a duplicate of https://github.com/wdecoster/NanoPlot/issues/201
Please downgrade seaborn to version 0.10.1

**Closed** 2022-09-28 08:00 UTC
