### ISSUE TITLE
PolyCollection' object has no property 'stat_func' error

### ISSUE THREAD

**Issue by Juliana-Soto24** [wdecoster/NanoPlot#293] opened 2022-04-07 15:02 UTC
Hi, 
I'm getting this error when I run: 
NanoPlot -t 30 --fastq SBI00225.fastq --maxlength 40000 --plots dot --legacy hex -o SBI00225

I have attached the log file

[NanoPlot_20220407_1054.log](https://github.com/wdecoster/NanoPlot/files/8444101/NanoPlot_20220407_1054.log)

Thanks, 
Juliana

**Comment by wdecoster** [comment] 2022-04-08 20:10
This seems a duplicate of https://github.com/wdecoster/NanoPlot/issues/222. Please try downgrading your seaborn installation to 0.10.1.

**Closed by wdecoster** 2022-04-08 20:10 UTC
