### ISSUE TITLE
AttributeError: Unknown property height

### ISSUE THREAD

**Issue by taffners** [wdecoster/NanoPlot#103] opened 2018-10-22 17:09 UTC
Hello

Here is my run command:

NanoPlot --fastq fastq_runid_fe24fa25f3bfad833de46efbd3e24c55dbeadf9e_0.fastq

I'm getting the follow error:

2018-10-22 13:05:04,128 NanoPlot 1.18.2 started with arguments Namespace(N50=False, alength=False, bam=None, barcoded=False, color='#4CB391', cram=None, downsample=None, dpi=100, drop_outliers=False, fasta=None, fastq=['fastq_runid_fe24fa25f3bfad833de46efbd3e24c55dbeadf9e_0.fastq'], fastq_minimal=None, fastq_rich=None, font_scale=1, format='png', listcolors=False, loglength=False, maxlength=None, minlength=None, minqual=None, no_N50=False, outdir='.', percentqual=False, pickle=None, plots=['kde', 'dot'], prefix='', raw=False, readtype='1D', runtime_until=None, store=False, summary=None, threads=4, title=None, verbose=False)
2018-10-22 13:05:04,129 Python version is: 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56)  [GCC 7.2.0]
2018-10-22 13:05:04,507 Nanoplotter: valid output format png
2018-10-22 13:05:04,549 Nanoget: Starting to collect statistics from plain fastq file.
2018-10-22 13:05:50,488 Reduced DataFrame memory usage from 0.3752288818359375Mb to 0.250152587890625Mb
2018-10-22 13:05:50,501 Nanoget: Gathered all metrics of 16394 reads
2018-10-22 13:05:50,525 Calculated statistics
2018-10-22 13:05:50,525 Using sequenced read lengths for plotting.
2018-10-22 13:05:50,525 Processed the reads, optionally filtered. 16394 reads left
2018-10-22 13:05:50,526 Nanoplotter: Valid color #4CB391.
2018-10-22 13:05:50,526 Nanoplotter: Creating length plots for Read length.
2018-10-22 13:05:50,526 Nanoplotter: Using 16394 reads maximum of 116013bp.
2018-10-22 13:05:54,516 Created length plots
2018-10-22 13:05:54,516 Nanoplotter: Creating Read lengths vs Average read quality plots using statistics from 16394 reads.
2018-10-22 13:05:54,715 Unknown property height
Traceback (most recent call last):
  File "/software/anaconda3/5.2.0b/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 92, in main
    plots = make_plots(datadf, settings)
  File "/software/anaconda3/5.2.0b/lib/python3.6/site-packages/nanoplot/NanoPlot.py", line 328, in make_plots
    plot_settings=plot_settings)
  File "/software/anaconda3/5.2.0b/lib/python3.6/site-packages/nanoplotter/nanoplotter_main.py", line 138, in scatter
    joint_kws={"s": 1})
  File "/software/anaconda3/5.2.0b/lib/python3.6/site-packages/seaborn/axisgrid.py", line 2247, in jointplot
    grid.plot_joint(plt.scatter, **joint_kws)
  File "/software/anaconda3/5.2.0b/lib/python3.6/site-packages/seaborn/axisgrid.py", line 1755, in plot_joint
    func(self.x, self.y, **kwargs)
  File "/software/anaconda3/5.2.0b/lib/python3.6/site-packages/matplotlib/pyplot.py", line 3470, in scatter
    edgecolors=edgecolors, data=data, **kwargs)
  File "/software/anaconda3/5.2.0b/lib/python3.6/site-packages/matplotlib/__init__.py", line 1855, in inner
    return func(ax, *args, **kwargs)
  File "/software/anaconda3/5.2.0b/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 4323, in scatter
    collection.update(kwargs)
  File "/software/anaconda3/5.2.0b/lib/python3.6/site-packages/matplotlib/artist.py", line 888, in update
    for k, v in props.items()]
  File "/software/anaconda3/5.2.0b/lib/python3.6/site-packages/matplotlib/artist.py", line 888, in <listcomp>
    for k, v in props.items()]
  File "/software/anaconda3/5.2.0b/lib/python3.6/site-packages/matplotlib/artist.py", line 881, in _update_property
    raise AttributeError('Unknown property %s' % k)
AttributeError: Unknown property height

**Comment by wdecoster** [comment] 2018-10-23 00:43
Duplicate of https://github.com/wdecoster/NanoPlot/issues/88

Please let me know if the proposed solution does not work.

**Comment by wdecoster** [comment] 2018-10-29 17:42
Closing due to lack of response, please let me know if the issue persists.

**Closed by wdecoster** 2018-10-29 17:42 UTC
