### ISSUE TITLE
NanoPlot 1.39 crashes halfway - ValueError raised from plotly

### ISSUE THREAD

**Issue by landmanf** [wdecoster/NanoPlot#283] opened 2021-12-02 11:23 UTC
Hi Wouter,
I'm trying to get NanoPlot to work in a environment with several other dependencies and it crashes halfway before finishing all of the .html it raises an ValueError from plotly 

I tried several versions of NanoPlot

Versions (1.35.5, 1.36.1,1.37.0, 1.38.0) gave " scatter() missing 1 required positional argument: 'data_frame' "  which I saw in an previous issue (#268 and was fixed in 1.38.1) so I tried those newer versions (1.38.1, 1.39.0) but they gave the ValueError from plotly

Hopefully it's an easy fix :)

Added the logfile:
[NanoPlot_20211202_0943.log](https://github.com/wdecoster/NanoPlot/files/7641437/NanoPlot_20211202_0943.log)

**Comment by wdecoster** [comment] 2021-12-02 12:31
Hi, that seems to be a duplicate of https://github.com/wdecoster/NanoPlot/issues/278, which is unfortunately unsolved as the one who reported that didn't follow up. 

My first idea is that you might have an outdated plotly module, could you check the version?
python -c "import plotly ; print(plotly.__version__)"

**Comment by landmanf** [comment] 2021-12-02 13:36
Thank you for the quick reply. 
This is the output:
<module 'plotly.version' from 'path/to/conda/envs/test_nanoplot2/lib/python3.8/site-packages/plotly/version.py'>

**Comment by wdecoster** [comment] 2021-12-02 13:41
Glad you caught my error in copy-pasting the command :-)

Could you just try upgrading plotly? At least that gives me a starting point on how to reproduce this...

**Comment by landmanf** [comment] 2021-12-02 13:52
Upgraded plotly to 5.4.0 and now NanoPlot 1.38.1 works perfect without errors. In the process of upgrading through pip it revealed the program holding plotly back which is PycoQC and says it requires plotly 4.1.0.

**Comment by wdecoster** [comment] 2021-12-02 13:54
Aha, that is remarkable but very good to know. I will change the minimal required version for NanoPlot then to 5.4.0... Thanks for the quick feedback!

**Comment by landmanf** [comment] 2021-12-02 14:09
Interestingly/luckily enough PycoQC (v2.5.2) still works in this environment as well when only supplying the --summary_file html and output.
Thank you for your help :)!

**Closed** 2022-01-21 10:24 UTC
